/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNISignalQuality */

#ifndef _Included_JNISignalQuality
#define _Included_JNISignalQuality
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNISignalQuality
 * Method:    nativeSignalQuality
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNISignalQuality_nativeSignalQuality
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
